// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IndexButton.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from IndexButton.proto</summary>
public static partial class IndexButtonReflection {

  #region Descriptor
  /// <summary>File descriptor for IndexButton.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static IndexButtonReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFJbmRleEJ1dHRvbi5wcm90byKgAQoLSW5kZXhCdXR0b24SDQoFaW5kZXgY",
          "ASACKAUSIQoFZXZlbnQYAiACKA4yEi5JbmRleEJ1dHRvbi5FdmVudBIUCgx0",
          "aW1lc3RhbXBfbXMYAyABKA0iSQoFRXZlbnQSDwoLRVZFTlRfRVJST1IQABIP",
          "CgtCVVRUT05fRE9XThABEg0KCUJVVFRPTl9VUBACEg8KC0JVVFRPTl9IRUxE",
          "EAM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::IndexButton), global::IndexButton.Parser, new[]{ "Index", "Event", "TimestampMs" }, null, new[]{ typeof(global::IndexButton.Types.Event) }, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class IndexButton : pb::IMessage<IndexButton>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IndexButton> _parser = new pb::MessageParser<IndexButton>(() => new IndexButton());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<IndexButton> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IndexButtonReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IndexButton() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IndexButton(IndexButton other) : this() {
    _hasBits0 = other._hasBits0;
    index_ = other.index_;
    event_ = other.event_;
    timestampMs_ = other.timestampMs_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IndexButton Clone() {
    return new IndexButton(this);
  }

  /// <summary>Field number for the "index" field.</summary>
  public const int IndexFieldNumber = 1;
  private readonly static int IndexDefaultValue = 0;

  private int index_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Index {
    get { if ((_hasBits0 & 1) != 0) { return index_; } else { return IndexDefaultValue; } }
    set {
      _hasBits0 |= 1;
      index_ = value;
    }
  }
  /// <summary>Gets whether the "index" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIndex {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "index" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIndex() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "event" field.</summary>
  public const int EventFieldNumber = 2;
  private readonly static global::IndexButton.Types.Event EventDefaultValue = global::IndexButton.Types.Event.Error;

  private global::IndexButton.Types.Event event_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::IndexButton.Types.Event Event {
    get { if ((_hasBits0 & 2) != 0) { return event_; } else { return EventDefaultValue; } }
    set {
      _hasBits0 |= 2;
      event_ = value;
    }
  }
  /// <summary>Gets whether the "event" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasEvent {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "event" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEvent() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "timestamp_ms" field.</summary>
  public const int TimestampMsFieldNumber = 3;
  private readonly static uint TimestampMsDefaultValue = 0;

  private uint timestampMs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TimestampMs {
    get { if ((_hasBits0 & 4) != 0) { return timestampMs_; } else { return TimestampMsDefaultValue; } }
    set {
      _hasBits0 |= 4;
      timestampMs_ = value;
    }
  }
  /// <summary>Gets whether the "timestamp_ms" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTimestampMs {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "timestamp_ms" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTimestampMs() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as IndexButton);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(IndexButton other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Index != other.Index) return false;
    if (Event != other.Event) return false;
    if (TimestampMs != other.TimestampMs) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasIndex) hash ^= Index.GetHashCode();
    if (HasEvent) hash ^= Event.GetHashCode();
    if (HasTimestampMs) hash ^= TimestampMs.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasIndex) {
      output.WriteRawTag(8);
      output.WriteInt32(Index);
    }
    if (HasEvent) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Event);
    }
    if (HasTimestampMs) {
      output.WriteRawTag(24);
      output.WriteUInt32(TimestampMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasIndex) {
      output.WriteRawTag(8);
      output.WriteInt32(Index);
    }
    if (HasEvent) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Event);
    }
    if (HasTimestampMs) {
      output.WriteRawTag(24);
      output.WriteUInt32(TimestampMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasIndex) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
    }
    if (HasEvent) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Event);
    }
    if (HasTimestampMs) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimestampMs);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(IndexButton other) {
    if (other == null) {
      return;
    }
    if (other.HasIndex) {
      Index = other.Index;
    }
    if (other.HasEvent) {
      Event = other.Event;
    }
    if (other.HasTimestampMs) {
      TimestampMs = other.TimestampMs;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Index = input.ReadInt32();
          break;
        }
        case 16: {
          Event = (global::IndexButton.Types.Event) input.ReadEnum();
          break;
        }
        case 24: {
          TimestampMs = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Index = input.ReadInt32();
          break;
        }
        case 16: {
          Event = (global::IndexButton.Types.Event) input.ReadEnum();
          break;
        }
        case 24: {
          TimestampMs = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the IndexButton message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Event {
      [pbr::OriginalName("EVENT_ERROR")] Error = 0,
      [pbr::OriginalName("BUTTON_DOWN")] ButtonDown = 1,
      [pbr::OriginalName("BUTTON_UP")] ButtonUp = 2,
      [pbr::OriginalName("BUTTON_HELD")] ButtonHeld = 3,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
