// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LT4FootswitchModeStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from LT4FootswitchModeStatus.proto</summary>
public static partial class LT4FootswitchModeStatusReflection {

  #region Descriptor
  /// <summary>File descriptor for LT4FootswitchModeStatus.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LT4FootswitchModeStatusReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1MVDRGb290c3dpdGNoTW9kZVN0YXR1cy5wcm90byJQChdMVDRGb290c3dp",
          "dGNoTW9kZVN0YXR1cxI1CgtjdXJyZW50TW9kZRgBIAIoDjINLkxUNEZ0c3dN",
          "b2RlczoRTFQ0X0ZUU1dfTU9ERV9PRkYqbQoMTFQ0RnRzd01vZGVzEhUKEUxU",
          "NF9GVFNXX01PREVfT0ZGEAASFwoTTFQ0X0ZUU1dfTU9ERV9CQU5LMRABEhcK",
          "E0xUNF9GVFNXX01PREVfQkFOSzIQAhIUChBMVDRfRlRTV19NT0RFX0ZYEAM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LT4FtswModes), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LT4FootswitchModeStatus), global::LT4FootswitchModeStatus.Parser, new[]{ "CurrentMode" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum LT4FtswModes {
  [pbr::OriginalName("LT4_FTSW_MODE_OFF")] Lt4FtswModeOff = 0,
  [pbr::OriginalName("LT4_FTSW_MODE_BANK1")] Lt4FtswModeBank1 = 1,
  [pbr::OriginalName("LT4_FTSW_MODE_BANK2")] Lt4FtswModeBank2 = 2,
  [pbr::OriginalName("LT4_FTSW_MODE_FX")] Lt4FtswModeFx = 3,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LT4FootswitchModeStatus : pb::IMessage<LT4FootswitchModeStatus>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LT4FootswitchModeStatus> _parser = new pb::MessageParser<LT4FootswitchModeStatus>(() => new LT4FootswitchModeStatus());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LT4FootswitchModeStatus> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LT4FootswitchModeStatusReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LT4FootswitchModeStatus() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LT4FootswitchModeStatus(LT4FootswitchModeStatus other) : this() {
    _hasBits0 = other._hasBits0;
    currentMode_ = other.currentMode_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LT4FootswitchModeStatus Clone() {
    return new LT4FootswitchModeStatus(this);
  }

  /// <summary>Field number for the "currentMode" field.</summary>
  public const int CurrentModeFieldNumber = 1;
  private readonly static global::LT4FtswModes CurrentModeDefaultValue = global::LT4FtswModes.Lt4FtswModeOff;

  private global::LT4FtswModes currentMode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LT4FtswModes CurrentMode {
    get { if ((_hasBits0 & 1) != 0) { return currentMode_; } else { return CurrentModeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      currentMode_ = value;
    }
  }
  /// <summary>Gets whether the "currentMode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCurrentMode {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "currentMode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCurrentMode() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LT4FootswitchModeStatus);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LT4FootswitchModeStatus other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CurrentMode != other.CurrentMode) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCurrentMode) hash ^= CurrentMode.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasCurrentMode) {
      output.WriteRawTag(8);
      output.WriteEnum((int) CurrentMode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasCurrentMode) {
      output.WriteRawTag(8);
      output.WriteEnum((int) CurrentMode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasCurrentMode) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CurrentMode);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LT4FootswitchModeStatus other) {
    if (other == null) {
      return;
    }
    if (other.HasCurrentMode) {
      CurrentMode = other.CurrentMode;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CurrentMode = (global::LT4FtswModes) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          CurrentMode = (global::LT4FtswModes) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
